apiVersion: v1
kind: Pod
metadata:
  name: php-pod
  labels:
    app: php-app
spec:
  containers:
    - name: php-container
      image: itishrishikesh/dummy-lamp:php
---
apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  ports:
  - port: 80
  selector:
    app: php-app